### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/esm_data/P24665_0.pt'

### ISSUE THREAD

**Issue by zas97** [tttianhao/CLEAN#19]
When running train-triplet.py or train-supconH.py I get the following error:

FileNotFoundError: [Errno 2] No such file or directory: './data/esm_data/P24665_0.pt'

I've already retrieved all the esms and './data/esm_data/P24665.pt' exist but './data/esm_data/P24665_0.pt' doesn't.

I checked the code and I found this 

```
def random_positive(id, id_ec, ec_id):
    pos_ec = random.choice(id_ec[id])
    pos = id
    if len(ec_id[pos_ec]) == 1:
        return pos + '_' + str(random.randint(0, 9))
    while pos == id:
        pos = random.choice(ec_id[pos_ec])
    return pos
```

If I understand correctly the bug comes from return pos + '_' + str(random.randint(0, 9)), I do not understand why the + '_' + str(random.randint(0, 9)) is needed. It seems to just create a filename that doesn't exist. Could you explain?

**Comment by tttianhao** [comment]
Hi, It is needed to handle the edge case where a certain EC number only has one enzyme sequence and needs to sample for a positive sequence. The error should be fixed as part of the latest commit.

**Comment by tobbyxy** [comment]
Hi @tttianhao  this error still exist and I recently cloned the latest version of clean

**Comment by tobbyxy** [comment]
Ignore. the solution is in the readME
